// File generated by FlutterFire CLI / Phase 1 bootstrap.
// Replace these values by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until configured, the app shows a Firebase setup screen.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured =>
      android.apiKey != 'REPLACE_ME' && ios.apiKey != 'REPLACE_ME';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not a Phase 1 target.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Business Buddy Phase 1 targets Android (and iOS later).',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMm-LjbCoDwPquPyWdzwzuqk0WrWfpZEw',
    appId: '1:870212127799:android:7b3a23e2d1cbdef81c43b2',
    messagingSenderId: '870212127799',
    projectId: 'business-buddy-cdc8f',
    storageBucket: 'business-buddy-cdc8f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6dgk21nht0SqPMeZZ8pyYcRKU3_y8V0',
    appId: '1:870212127799:ios:36ee01315442f00f1c43b2',
    messagingSenderId: '870212127799',
    projectId: 'business-buddy-cdc8f',
    storageBucket: 'business-buddy-cdc8f.firebasestorage.app',
    iosBundleId: 'com.businessbuddy.businessBuddy',
  );
}
